# Generated by Django 5.2.6 on 2025-09-23 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('costo', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('contrasena', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_esp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('run', models.CharField(db_column='RUN', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=100)),
                ('email', models.EmailField(db_column='EMAIL', max_length=255, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='FECHA_NACIMIENTO', null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20)),
                ('direccion', models.TextField(blank=True, db_column='DIRECCION')),
                ('password', models.CharField(db_column='PASSWORD', max_length=128)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, db_column='IS_STAFF', default=False, null=True)),
                ('is_superuser', models.BooleanField(blank=True, db_column='IS_SUPERUSER', default=False, null=True)),
                ('date_joined', models.DateTimeField(blank=True, db_column='DATE_JOINED', default=django.utils.timezone.now, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='LAST_LOGIN', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'AUTOFIXCHILE_CLIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagoAtencion',
            fields=[
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=15)),
                ('atencion', models.OneToOneField(db_column='ATENCION_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='autofixchile.atencion')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='cliente',
            field=models.ForeignKey(db_column='CLIENTE_run_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='autofixchile.cliente'),
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('run_mecanico', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_mc', models.CharField(max_length=20)),
                ('apellido_mc', models.CharField(max_length=20)),
                ('email_mc', models.CharField(max_length=50)),
                ('fecha_nacimiento_mc', models.DateField()),
                ('telefono_mc', models.IntegerField()),
                ('direccion_mc', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.ForeignKey(db_column='ESPECIALIDAD_id', on_delete=django.db.models.deletion.CASCADE, to='autofixchile.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='mecanico',
            field=models.ForeignKey(db_column='MECANICO_run_mecanico', on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='autofixchile.mecanico'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('fecha_encargo', models.DateField()),
                ('cliente', models.ForeignKey(db_column='CLIENTE_run_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='autofixchile.cliente')),
                ('mecanico', models.ForeignKey(db_column='MECANICO_run_mecanico', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_asignados', to='autofixchile.mecanico')),
            ],
        ),
    ]
